### ISSUE TITLE
Document role of userdata.txt

### ISSUE THREAD

**Issue by jpvantuyl** [SDBrett/mcsa_lab#1]
What does it look like?

Where does it go?

What does it do?

It'd be nice to put that in the readme.  I'm assuming that it helps to inject scripts during build.

**Comment by jpvantuyl** [comment]
Also, I heard about you on the Datanaughts podcast.  Great stuff.  Keep up the good work!

**Comment by SDBrett** [comment]
There's a lot that I need to add to the README, I'm behind where I wanted to be by now. Life got in the way. 
I'm about to record a video 'how to' and after that, I'll be updating the README file.
